### PR TITLE
(maint) Add chocolatey/home for Stale workflow

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Adds the chocolatey/home repository for the stale workflow.

## Motivation and Context
Need the stale workflow in there for issues.

## Testing
N/A

### Operating Systems Testing
N/A

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v3 compatibility checked?

## Related Issue
N/A

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@pauby your changes have been merged. Thanks for your contribution 👍

**Comment by AdmiringWorm** [comment]
@pauby it looks like choco-sync-bot (or the group it is part of) does not have access to the https://github.com/chocolatey/home repository, causing the workflow to fail.

Any chance of updating the home repository with the same permissions that is set on https://github.com/chocolatey/choco?

**Comment by pauby** [comment]
> @pauby it looks like choco-sync-bot (or the group it is part of) does not have access to the https://github.com/chocolatey/home repository, causing the workflow to fail.

Closing the loop on this - it's been done.

**Pull request merged**
