### PR TITLE
(doc) Add Security Policies and Procedures

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Added the Security Policies and Procedures as taken from chocolatey/choco repository

## Motivation and Context
This lives in the .github folder of each repository, so it makes sense to have it here to (hopefully) propagate to other repositories using these standard templates.

## Testing
This is a markdown change so hasn't been tested.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

N/A.

## Change Checklist

* [x] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by pauby** [comment]
I wonder if we should use an [update to config.yml](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) instead?

**Comment by AdmiringWorm** [comment]
> I wonder if we should use an [update to config.yml](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) instead?

In the terms of adding the `SECURITY.md` file, we don't need to. It is an automatic item that would be present (assuming it isn't overridden by something else)

**Review by AdmiringWorm — APPROVED** [review]
LGTM. But I'll wait on @gep13 to have a look as well since you requested a review from us both.

**Comment by pauby** [comment]
> In the terms of adding the `SECURITY.md` file, we don't need to. It is an automatic item that would be present (assuming it isn't overridden by something else)

I'm not sure what you mean by this? If we don't need to add it should we close this PR?

**Pull request merged**
