### PR TITLE
(maint) Synchronize files to NuGet.Client

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description Of Changes

These changes include syncronizing the labels and
the pull request template to our fork of NuGet.Client.

## Motivation and Context

This allows us to be sure that we use the same labels and pull request in that repository without having to manually verify it every time.

## Testing

N/A

### Operating Systems Testing

N/A

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Additional details

The same changes that was made in chocolatey/docs needs to be made for NuGet.Client.
IE to give `choco-sync-bot` write access to the repository.

### CODE REVIEW

**Review by pauby — CHANGES_REQUESTED** [review]
Thanks for putting this in @AdmiringWorm

**Comment by AdmiringWorm** [comment]
@pauby Can you tell me what you want me to change in this PR?

I can not see any requested changes or comments have been made, just a comment that is request changes but with nothing else.

**Comment by pauby** [comment]
Given the comment I made in the review, I can only assume it was an accidental request for changes.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@AdmiringWorm thanks for getting this updated!

**Pull request merged**
