### PR TITLE
(#11) Add synchronization of files to remote repositories

### LINKED ISSUE #11: Setup file synchronization to sync common files to owned repositories
## Is Your Feature Request Related To A Problem? Please describe.

There are times where we have common configuration and documentation files that needs to be updated on other repositories.

## Describe The Solution. Why is it needed?

Set up a workflow that runs on this repository that will sync any configured files to the repositories that we have configured to be synced against.

## Additional Context.

N/A

## Related Issues

N/A

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description Of Changes

This pull request adds a basic configuration file and a workflow to be able to synchronize files to other repositories.
Only repositories that are public, not empty, will currently be synchronized.

This will require the `choco-sync-bot` to have write access to all the listed repositories.

## Motivation and Context

To keep files up to date.

## Testing

1. A similar approach is being used in my own private organization. Unfortunately it is not possible to be 100% sure that it works as intended until it is merged.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #11

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Moving this to draft until #12 is merged

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by AdmiringWorm** [comment]
This PR has been rebased and should be ready to be merged after `choco-sync-bot` have the correct permissions on all repositories listed in `sync.yml`.

Do note I recommend waiting on merging this PR until https://github.com/chocolatey/docs/pull/550 is merged

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
Let's take this for a spin, on just the docs repository for now, and we can open it up from there.

**Pull request merged**
